# Generated by Django 4.0b1 on 2022-01-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='my blog', max_length=255),
        ),
    ]
