# Generated by Django 4.0 on 2022-01-15 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_post_snippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='snippet',
        ),
    ]
