# Generated by Django 4.0 on 2022-01-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_remove_post_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
